name: PR

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  conventional:
    name: Semantic Pull Requests
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: wow-actions/semantic-pull-requests@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
